version: '3.8'

services:
  db:
    image: mysql:8.3.0
    container_name: planner-database
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    image: jorgegdoliveira8/planner-backend
    build:
      context: .
      dockerfile: Dockerfile
    container_name: planner-backend
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  mysql-data:
